/*
Deployment script for IdentitySideBySide

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "IdentitySideBySide"
:setvar DefaultFilePrefix "IdentitySideBySide"
:setvar DefaultDataPath "C:\Users\Harry\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\Harry\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[DeviceCodes]...';


GO
CREATE TABLE [dbo].[DeviceCodes] (
    [UserCode]     NVARCHAR (200) NOT NULL,
    [DeviceCode]   NVARCHAR (200) NOT NULL,
    [SubjectId]    NVARCHAR (200) NULL,
    [ClientId]     NVARCHAR (200) NOT NULL,
    [CreationTime] DATETIME2 (7)  NOT NULL,
    [Expiration]   DATETIME2 (7)  NOT NULL,
    [Data]         NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_DeviceCodes] PRIMARY KEY CLUSTERED ([UserCode] ASC)
);


GO
PRINT N'Creating [dbo].[DeviceCodes].[IX_DeviceCodes_Expiration]...';


GO
CREATE NONCLUSTERED INDEX [IX_DeviceCodes_Expiration]
    ON [dbo].[DeviceCodes]([Expiration] ASC);


GO
PRINT N'Creating [dbo].[DeviceCodes].[IX_DeviceCodes_DeviceCode]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DeviceCodes_DeviceCode]
    ON [dbo].[DeviceCodes]([DeviceCode] ASC);


GO
PRINT N'Creating [dbo].[PersistedGrants]...';


GO
CREATE TABLE [dbo].[PersistedGrants] (
    [Key]          NVARCHAR (200) NOT NULL,
    [Type]         NVARCHAR (50)  NOT NULL,
    [SubjectId]    NVARCHAR (200) NULL,
    [ClientId]     NVARCHAR (200) NOT NULL,
    [CreationTime] DATETIME2 (7)  NOT NULL,
    [Expiration]   DATETIME2 (7)  NULL,
    [Data]         NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_PersistedGrants] PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[PersistedGrants].[IX_PersistedGrants_SubjectId_ClientId_Type]...';


GO
CREATE NONCLUSTERED INDEX [IX_PersistedGrants_SubjectId_ClientId_Type]
    ON [dbo].[PersistedGrants]([SubjectId] ASC, [ClientId] ASC, [Type] ASC);


GO
PRINT N'Creating [dbo].[PersistedGrants].[IX_PersistedGrants_Expiration]...';


GO
CREATE NONCLUSTERED INDEX [IX_PersistedGrants_Expiration]
    ON [dbo].[PersistedGrants]([Expiration] ASC);


GO
PRINT N'Update complete.';


GO
